appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WhCK43BBRenR7kRD6LPoBjhI8T83AZ13xUQYxloKYn4vWFOvwB8IihjsK1NWlCnGu5ikCI+I0xsW9Xpt65bjS8QfVElASzCHuSxEiB9EAIKk0vYkbQ/B6j9ayiLGF3ZkrG85voEsi3aL/CON9RcnaSmpX1LvbnbnWLRq2oDE+F0UXuaalZAemaGNZVU9Sy6RRJH8N9AooRjvAobrSm8KObRCv6B9yamp8picdeEC2DOxhjeo4csvlN4LMVczznDNKIDah0WQ7eftEskrtOToV9qNs9DoUuxV9E5yOSFCGpP1GKBEiugMspFuS9syqpMT9OrT2Z2UeTcWicNis7hXlILZadIbFWS/EzN6EMa/x7Bqo6/oD3kvdusfaI1lmo5qXYfrpH8C2NQiAmkl4lJNhuSupjwsnBX5R1SXmp0SlOVLzLT0o0JPcz3dioibhXcnUHnkQXbRJSiZwvIOjxWxcVwuNWbNHPngXIABzH8MY0vhhxD8VejqcxQZhJhcb7reee/7kTze/G5VxhKMyjY+705u0ys9Qfx5qQWW3k3cbw0403Llhuj6rJ5JAQTCPisal6CM93Qqt3poZ+bnRjB8q3px8Vr9uxy6HtXMqDQ9dYOPzRUQOhPpa8z9JyT7gl5jl3QPvlk0qJxcxa9/RhHqljwOk2XF8M2YNOTevK68g50=}
