travis:
  secure:
    BINSTAR_TOKEN: v67KJdLmRLF9G3X9baiK2L5MAA3yaWQXgZLULULAHaxtzeIPNea1TDHY4Q5RWb40Kd8rNLunXRzKcj7RYd3KlduS/s+rz2EOvFJNbqx7XUpf6+vMFwR+digVjAWkXa0AL2FTqAWBb0dUCofKvVlAvBQIcvlySHfEBTdoiijChf7aLfw7rwXMJA/hBfVY1vDoEb8f16Z2i4Pg89i6KuyR+mD/MPxx9ComlYjLwL715C4oHGt3/8kLx/upzDVNjm6dMmYRld+EC9T1ZmLPXZVAOlUo+BvIWSGnLE2f6WDywUupRikovS0RDC9BU9HZ4EM6r2Zz0qHqJb5saoi0qEMG0aQS9coE8c3A1SnLLMRX5JZ2udYx+KLCXwTK8aI+HdaJpoRylIvR3ge0j+c4rm1xg8w0az3+qCp0XEyCyjyAHbSzKx7FLkS3O42mItP5OInS7vf5xkWD1Cb7MV0WPK0nGhfPS08+Lw9zZeeyf9Cw+Dr0+ZonLy969mTIJN6Eh39izkshWujSFIequ+PJMCgVTxkqNELodLN8gTmvEcT726O2vSKTH75HLVZYx+lhJA2SYvdCE2k+EDY4sIwc5aBMRhXPyYxHgcRplDDh1rNirb62U8d3Um3YbYm+livZlrjmBtAqEBg7ZqIyJyFrGsWaimONy/YYX9dNzKqZjnl2Pxo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
